# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "2048"
  end

  # config.vm.network :private_network, ip: "192.168.68.8"

  config.vm.provision "shell", inline: <<-SHELL
    
    add-apt-repository -y ppa:webupd8team/java
    apt-get update
    apt-get -y upgrade
    echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections 
    echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
    apt-get -y install oracle-java8-installer
    
    sudo apt-get install -y xfce4 virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11
    sudo apt-get install gnome-icon-theme-full tango-icon-theme
    sudo echo "allowed_users=anybody" > /etc/X11/Xwrapper.config
  
    sudo wget --progress=bar:force -O /opt/eclipse-java-luna-SR2-linux-gtk-x86_64.tar.gz http://ftp.fau.de/eclipse/technology/epp/downloads/release/luna/SR2/eclipse-java-luna-SR2-linux-gtk-x86_64.tar.gz
    cd /opt/ && sudo tar -zxvf eclipse-java-luna-SR2-linux-gtk-x86_64.tar.gz

	# LOCALE
	sudo apt-get install -y language-pack-fr
  
	echo "LANG=fr_CH.utf8" > /etc/default/locale
	echo "LC_MESSAGES=POSIX" >> /etc/default/locale

	# clavier suisse
	sudo loadkeys ch
	
	# TZ
    echo "Setting TimeZone Europe/Zurich"
	timedatectl set-timezone Europe/Zurich

  SHELL

  # Maven 3
  config.vm.provision "shell", inline: <<-SHELL
  
	apt-get -y install maven
	
  SHELL

  # Mirth Connect Administrator	  
  config.vm.provision "shell", inline: <<-SHELL
  
    sudo wget --progress=bar:force http://downloads.mirthcorp.com/connect/3.2.2.7694.b68/mirthconnect-3.2.2.7694.b68-unix.tar.gz -O /opt/mirthconnect-3.2.2.7694.b68-unix.tar.gz 
  	sudo mkdir /opt/mirthconnect
    cd /opt/ && sudo tar -zxvf mirthconnect-3.2.2.7694.b68-unix.tar.gz -C /opt/mirthconnect --strip-components=1
	sudo ln -s /opt/mirthconnect/mcservice /etc/init.d/
	sudo update-rc.d mcservice defaults
	sudo service mcservice start
	# sleep 10
	
  SHELL
  
  config.vm.provision "shell", inline: <<-SHELL

    sudo wget --progress=bar:force -O /opt/mirthconnectcli-3.2.2.7694.b68-unix.tar.gz http://downloads.mirthcorp.com/connect/3.2.2.7694.b68/mirthconnectcli-3.2.2.7694.b68-unix.tar.gz
    cd /opt/ && sudo tar -zxvf mirthconnectcli-3.2.2.7694.b68-unix.tar.gz

  SHELL
    
  # trigger reload
  # config.vm.provision :reload
 
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
  
	mkdir ~vagrant/Desktop
	touch ~vagrant/Desktop/mirth-connect.jnlp
	wget --retry-connrefused -t 20 -w 2 http://localhost:8080/webstart.jnlp -O ~vagrant/Desktop/mirth-connect.jnlp 
	
  SHELL
   
end
